
name: Publish
on:
  pull_request:
    branches:
    - master
    types: [labeled]

jobs:
  merge:
    if: github.event.label.name == 'gate'
    name: merge
    runs-on: ubuntu-latest
    steps:
    - name: echo gh
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"



